Html css feature
rychrr/hello_microverse pull request #1
Opened 2023-03-23 01:26 UTC by rychrr

Hi ,

I have created a new feature branch called  - **html-css- features** . 

Here are the additions in the **html-css-features: 
- Updated the  index.html page
- included a CSS styling on the header
- Included HTML & CSS Linters and lighthouse to help improve the script , web page and manage syntax errors

Please review  the pull request and let me know should there be any changes required. 

Regards, 
Ejike

2023-03-23 02:21 UTC, Shedrack-Sunday requested changes
Hi @rychrr       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights:
✔️ good use of .gitignore
✔️ good PR summary
  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required below need to be implemented :
- Some sections of your README such as future fears is not added. kindly check the image below to see the sections missing
- Your linters seem to be failing. kindly fix this

## Section:
![image](https://user-images.githubusercontent.com/50990925/227082529-4e3dac83-1016-47bf-915c-2df98385d891.png)



_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] This section of the codebase is meant to help you with things to add to the section. Kindly delete it to keep your codebase clean 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] For this section, please check my comment on line `40` on why it should be deleted 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] For this section, please check my comment on line `40` on why it should be deleted 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +> Link to deployed project.
- [ ] For this section, please check my comment on line `40` on why it should be deleted 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +> collaborators of this project.
- [ ] For this section, please check my comment on line `40` on why it should be deleted 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [ ] This section has a duplicate Author, and one should be deleted. 
- Also, edit the socials with your details to give people a way to contact you 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] For this section, please check my comment on line `40` on why it should be deleted 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Please kindly edit this section to state the features your project currently possesses. This gives users a general overview on the features of the code 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] For this section, please check my comment on line `40` on why it should be deleted 👍

2023-03-23 02:21 UTC, Shedrack-Sunday commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] This section of the README is meant to be an instruction but not added to the project. Always try to personalize your project as much as possible 👍

2023-03-24 06:05 UTC, rychrr commented on README.md
> +
Hi, @Shedrack-Sunday ,

Thanks, All cases of has been resolved.

2023-03-24 06:05 UTC, rychrr commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
Thanks for spotting this out,

I have updated this as well,

2023-03-24 06:06 UTC, rychrr commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
This is noted too @Shedrack-Sunday , Thanks a bunch

2023-03-24 06:12 UTC, rychrr commented
Hi @Shedrack-Sunday ,

I have made the adjustments, can you take another look

Regards,

2023-03-24 07:16 UTC, wayungi requested changes
Hi @rychrr , 

![image](https://user-images.githubusercontent.com/99656687/224544249-9b993818-f5f3-4997-ae19-af0d410b03c4.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [x] All linter checks passing ✔️ 
- [ ] Good commit messages ✔
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ OPTIONAL ] Kindly be consistent in your Commit message tense. It should be the Imperative tense and always remember to capitalize the first word. 🤝  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 07:16 UTC, wayungi commented on README.md
> +- [Live Demo Link](https://hellomverse.com)
- [OPTIONAL] Your live demo link is broken. You can instead clearly indicate that there is no live demo by replacing the link with the text "Live demo coming so" or "N/A" , meaning not applicable since the project does not require you to ave a live demo.
![demo](https://user-images.githubusercontent.com/99656687/227448707-545d6221-0476-450d-b469-46e3958e82a9.png) ✍🏾

2023-03-24 07:16 UTC, wayungi commented on README.md
> +
- [ OPTIONAL ] Since the project does not require tests, You can clearly indicate that tests are not required by adding **Not applicable**
![tests](https://user-images.githubusercontent.com/99656687/227449949-69860e90-7253-4264-b953-b55bd009d6ea.png) 🤔

2023-03-24 08:40 UTC, rychrr commented on README.md
> +
@wayungi , 
Thanks, I missed that bit, this has been fixed.

2023-03-24 08:40 UTC, rychrr commented on README.md
> +
Fixed

2023-03-24 08:41 UTC, rychrr commented
All fixed now, 

Typo errors were also fixed

2023-03-24 08:44 UTC, AdnanOlarmmi approved these changes
Hi @rychrr,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice work ignoring appropriate files.
- Professional README.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 09:29 UTC, merged